### PR TITLE
add hardware support for customize servo speed

### PR DESCRIPTION
**Pull request by superyarik**
Problem: servo down to egg to fast, it can create fat dots at landing place. in EggBot PlugIn we can change speed of servo, but it useless, because where is no support in adriono code.

in GUI we can change servo speed in range 1-1600, when https://github.com/evil-mad/EggBot send it to EggDuino it multiply by 5. So we have range 5-8000, which support i've add

### CODE REVIEW

**Comment by uChip** [comment]
Why close?  Did changes not work?  I need something similar so I can create an EggDuino engraving function.  Otherwise fast penDown will smash engraving tip into workpiece and break it.

**Comment by superyarik** [comment]
@uChip it work, but i found that:
1) i forget to save speed of servo to EPPROM
2) i found repository https://github.com/schlion/EggDuino where it allready implemented with saving to EPPROM

**Comment by uChip** [comment]
Thank you for answering. I will look at that repository.

**Comment by uChip** [comment]
I now know more about searching for repositories on GitHub. :)

Anyone looking for EggDuino should look at the list of forks.  This repository is neither the root fork nor the most advanced.  I suggest looking at fork https://github.com/papabricole/EggDuino which seems to be more up-to-date and supports a wide variety of Arduino variants.

**Comment by superyarik** [comment]
Yep, i also find it, but there is indeed heavy refactored structure and it is hard for me read some constructions, cause i'm not c++ developer. Servo speed and buttons implemented in schlion repository as well, i can't find feature difference in this reps. Also i have CNCShield in use, so schlion rep is more friendly for me :)

**Comment by uChip** [comment]
I am digging into the code details.  I can read it but I agree that the coding style is not as readable.

**Pull request closed without merging**
